[package]
name = "raftnode"
version = "0.1.0"
edition = "2024"

[dependencies]
mio = { version = "1.1.1", default-features=false, features = ["os-poll", "net"] }
nojson = "0.3.6"
raftbare = "0.2.1"
rand = "0.9.2"
